### ISSUE TITLE
Scrolling Native Video Element on Android

### ISSUE THREAD

**Issue by msach22** [opentok/cordova-plugin-opentok#10]
The Cordova OpenTok plugin uses the native OpenTok SDKs and places native iOS and Android views for the Publisher and Subscriber on top of a WebView. On Android, when you scroll on the WebView, the native video element does not and the video is stuck in its initial position.

**Comment by mark-veenstra** [comment]
@msach22 Do you have a bit of an idea what should be done here to get this fixed? Maybe if you point us into a direction we can take a look and send a PR.

**Comment by msach22** [comment]
Fixed by: https://github.com/opentok/cordova-plugin-opentok/pull/28
