### ISSUE TITLE
It is working on browser but not working on iphone 

### ISSUE THREAD

**Issue by josh0203be** [opentok/cordova-plugin-opentok#105]
HI 
I am  using  this SDK on my ionic project. but this is not working on iphone 
I got this error. Could you help me asap , please ? 
I attached error screen 
[http://prntscr.com/jpj6hw](http://prntscr.com/jpj6hw)
Thanks for your time

**Comment by msach22** [comment]
@josh0203be Could you please confirm that you've followed the instructions here? https://github.com/opentok/opentok-ionic-samples

**Comment by josh0203be** [comment]
I cloned Basic Video Chat repository and install npm
But get errors 
"cannot find variable OT"
Would you explain to me about that?

**Comment by msach22** [comment]
Can you verify that you added the plugin using `ionic cordova plugin add cordova-plugin-opentok`?

**Comment by josh0203be** [comment]
Yes
I've installed

**Comment by josh0203be** [comment]
That's what I want to ask you
What is the "over the files"?

**Comment by msach22** [comment]
[`ionic serve`](https://ionicframework.com/docs/cli/serve/) launches a dev server and creates a build which can be used

**Comment by josh0203be** [comment]
Yeah, so which files should I copy to the www folder?

**Comment by msach22** [comment]
The `ionic serve` command does that for you and prepares a build.

**Comment by josh0203be** [comment]
Then?

**Comment by josh0203be** [comment]
Ofcourse I have run "ionic serve"
And then clicked "Start OpenTok Call"
Then it says "OT is not defined"

**Comment by josh0203be** [comment]
Perhaps it's version problem?

**Comment by msach22** [comment]
@josh0203be Please follow the instructions on the README which walks you through how to prepare for an iOS application. I'm unable to reproduce the issue that you're having. 

https://github.com/opentok/opentok-ionic-samples#for-ios

**Comment by msach22** [comment]
@josh0203be I'm unable to reproduce the issue that you're having. Could you please confirm that you've followed each step in the `Running the Application` section for iOS?https://github.com/opentok/opentok-ionic-samples#for-ios

**Comment by msach22** [comment]
@josh0203be Did this work for you?

**Comment by josh0203be** [comment]
Yes it is working Thanks for your help

**Comment by msach22** [comment]
Happy to help, @josh0203be. I'm glad it's working for you!
