### ISSUE TITLE
Browser haven´t support to WebRTC

### ISSUE THREAD

**Issue by brunosoune** [opentok/cordova-plugin-opentok#106]
I have the error "Browser haven´t support to WebRTC" to IOS

I added the plugin cordova-plugin-opentok and the npm install --save @opentok/client to use @opentok/client/dist/js/opentok.min.js on html...

It work fine to desktop web browser, safari browser in iphone and compiled app android. But in compiled app iphone occur the error above.

**Comment by msach22** [comment]
The iOS webview does not support webrtc so you cannot use the JS SDK to run it in an iOS app. You have add this plugin and use the JS wrapper from this plugin to run OpenTok on your iOS app

**Comment by brunosoune** [comment]
plugins\cordova-plugin-opentok\www\opentok.js ?
I should use this to android too?

**Comment by msach22** [comment]
Yes, that's correct! You can use the JS SDK and run it in an Android WebView, but I recommend sticking with the plugin so you can leverage the native SDKs.

**Comment by brunosoune** [comment]
Ok @msach22 

I'll try your recommendation and I'll post any result here.

Thanks a lot

**Comment by msach22** [comment]
@brunosoune Since this is not an issue with the plugin, I'm going to close this issue. Please feel free to re-open if you have issues using the plugin!

**Comment by msach22** [comment]
@brunosoune Yes, it should be working. I recommend checking out the samples here: https://github.com/opentok/opentok-cordova-samples/

**Comment by brunosoune** [comment]
In your samples you use this way:

`session.connect(token, function() {
          // publish to the session
          session.publish(publisher);
        });
`
But in tokbox's examples is:
`session.connect(token, function(error) {
   if (error) {
     console.log(error.message);
   } else {
     session.publish(publisher);
   }
 });`

There are some difference use the if (error).... ?

**Comment by msach22** [comment]
Here's the issue: https://github.com/opentok/cordova-plugin-opentok/issues/107

**Comment by brunosoune** [comment]
ok @msach22 

thanks
