### ISSUE TITLE
Does opentok cordova plugin, support (pause, resume and annotation) on video?

### ISSUE THREAD

**Issue by Gopalagithub** [opentok/cordova-plugin-opentok#119]
We are unable to get the image data from the .getImgData() function using opentok.js file in plugin for IoS hybrid application using cordova-plugin-opentok.

opentok.min.js works in safari and doesn't in ios app, any other alternative plugin which will support all the bellow mentioned features

1) Basic Video/Audio Call.
2) Pause/Resume Feature.
3) Annotation.

**Comment by wolfenrain** [comment]
The [`.getImgData()`](https://github.com/opentok/cordova-plugin-opentok/blob/master/src/js/OTPublisher.coffee#L91) is not yet implemented with the JS bridge. Ofcourse it works with the `opentok.min.js` in a browser(safari in this case). Thats because its a different library.

**Comment by Gopalagithub** [comment]
Thanks for the input @wolfenrain, Is there any other libraries with the above functionalities?

**Comment by msach22** [comment]
@Gopalagithub As @wolfenrain mentioned, the native SDKs don't have a method for capturing a screenshot, but you could implement a Custom Capturer to capturer the contents of the stream:
- Android: https://tokbox.com/developer/tutorials/android/custom-camera-video-capturing/
- iOS: https://tokbox.com/developer/tutorials/ios/custom-camera-video-capturing/

**Comment by msach22** [comment]
Closing this issue because `getImgData` has been implemented as of v3.4.0
