### ISSUE TITLE
Problem Building with Ionic Package

### ISSUE THREAD

**Issue by mfossel** [opentok/cordova-plugin-opentok#12]
Hello, thank you for this plugin but I am having a problem building with Ionic. We are using Ionic Pro and whenever we try to build for Androidwith Ionic Package we get an error on this plugin.

`Failed to restore plugin "com.tokbox.cordova.opentok" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin https://github.com/opentok/cordova-plugin-opentok via registry.
`

I know you have examples using Ionic. Can you help us with this?

**Comment by msach22** [comment]
@mfossel Hmm, I have not been able to replicate this error, although I've only tested it with Ionic 2. Is the following how you're adding the plugin?
`ionic cordova plugin add https://github.com/opentok/cordova-plugin-opentok/`

Could you try cloning https://github.com/opentok/opentok-ionic-samples and seeing if that works for you?

**Comment by mfossel** [comment]
Yes, that is how I installed it.

We are using Ionic 2. Trying to build with Ionic Pro Package when we get the error.

This is in my config.xml
  `  <plugin name="com.tokbox.cordova.opentok" spec="https://github.com/opentok/cordova-plugin-opentok" />`

this is in my package.json
`    "Cordova-Plugin-OpenTok": "git+https://github.com/opentok/cordova-plugin-opentok.git"`

Ionic seems to have some problem grabbing the plugin from github

I can clone your example but that would require registering a new app with Ionic or overriding what I currently have, so I am trying to figure it out before I attempt that.

**Comment by mfossel** [comment]
Hey, just got it working. I changed my config.xml from
`<plugin name="com.tokbox.cordova.opentok" spec="https://github.com/opentok/cordova-plugin-opentok" />`
to
`<plugin name="com.tokbox.cordova.opentok" spec="https://github.com/msach22/cordova-plugin-opentok" />`

after looking through your example and my build succeeded.

**Comment by msach22** [comment]
@mfossel To clarify, you were able to download this plugin (under opentok) after you changed the plugin spec to the plugin hosted under my personal account?

**Comment by mfossel** [comment]
Yes, Ionic Package was able to download and build after I switched it. For some reason it was not able to fetch the plugin from the opentok host.
