### ISSUE TITLE
Add getImgData

### ISSUE THREAD

**Issue by msach22** [opentok/cordova-plugin-opentok#121]
# Feature Request
The OpenTok JS SDK supports the `getImgData` functionality. We should be able to use `getImgData` for iOS and Android as well. 
**Description**
> (Include problem, use cases, benefits, and/or goals)

**Proposal**

**Links / references**

**Comment by wolfenrain** [comment]
If we can extract the base64 data from it then yes, it would be doable

**Comment by msach22** [comment]
Yes, we can do that by implementing something like this:
https://github.com/opentok/opentok-ios-sdk-samples-swift/tree/master/Live-Photo-Capture/Live-Photo-Capture

**Comment by wolfenrain** [comment]
Would come with its own side effects. We should take each option into consideration properly(maybe with some tests) to see what would be viable and least "destructive"(at lack of words).

**Comment by msach22** [comment]
Released with 3.4.0
