### ISSUE TITLE
Can't start broadcast with back facing camera

### ISSUE THREAD

**Issue by iisdan** [opentok/cordova-plugin-opentok#13]
## Expected Behavior
Start a new broadcast with the back facing camera.

## Actual Behavior
Live stream starts with front facing camera. I have checked openTok.js and the property is being set, only ignored. 

## Steps to Reproduce the Problem

  1. Set cameraName  in publisher options to `var publisherOptions = { cameraName: 'back' };`
  2. Init Publisher `OT.initPublisher('publisher', publisherOptions);`

## Specifications

  - Version: Newest
  - Platform: Android

**Comment by msach22** [comment]
@iisdan thanks for pointing this out. Fixed here: https://github.com/opentok/cordova-plugin-opentok/pull/18
