### ISSUE TITLE
Does this plugin support iOS annotation using opentok-annotation package ? 

### ISSUE THREAD

**Issue by SohanMShetty** [opentok/cordova-plugin-opentok#139]
We tried implementing annotation in iOS ionic application using cordova-plugin-opentok and opentok-annotation package, but we failed to do. is there any possibility to achieve this?

we published the canvas stream through videoSource attribute as given in below code, in publisher end annotation is happening, but in subscriber end annotation is not reflecting.
```
 this.publisher = OT.initPublisher(this.publisherDiv.nativeElement,
      {
        insertMode: 'append', name: 'PauseScreen',
        width: 100, height: 720,
        videoSource:this.visualization.nativeElement.captureStream(1).getVideoTracks()[0]
      });

this.session.publish(this.publisher, function (error) { });
```

**Comment by msach22** [comment]
@SohanMShetty Thanks for filing an issue. This plugin does not work with the annotations package because it was built for web. Please note that this plugin uses the native SDKs.
