### ISSUE TITLE
Why use - (void)logOT function.

### ISSUE THREAD

**Issue by LokeshPatel** [opentok/cordova-plugin-opentok#14]
Hello,
I need more details of logOT function,  this is use in both platform iOS and Android.
Call API : https://hlg.tokbox.com/prod/logging/ClientEvent for send details , params 
like : platform, cp_version , action , partner_id , build , source , payload_type, payload, session_id

iOS : - (void)logOT;
Android : -   public void logOT();

I tried to find in details on Tokbox doc but not getting proper  details related to this api.

Please suggest me why use this method bcz this method called automatically with initSession methods.Also please suggest me impact of this method in can remove this method.

Thanks in Advance :)

**Comment by msach22** [comment]
@LokeshPatel The `logOT` method is used to log the initSession activity. This allows us to track the usage and debug. We also use this as one of the metrics when we discuss if we plan to support Cordova or not. Having said that, if you were to remove the logging method, the plugin should still work as expected.
