### ISSUE TITLE
Several publisher and subscriber events don't fire

### ISSUE THREAD

**Issue by msach22** [opentok/cordova-plugin-opentok#140]
# Bug Report

**Current behavior**
The audiolevel and network stats event listeners for the subscriber don't fire. This is because the native code is not registering the proper delegates and event listeners on iOS/Android.

**Steps to reproduce**
For example, the following would not result in any console log statements even when the event fires.

```javascript
subscriber.on({
  audioLevelUpdated: event => {
    console.log('event', event);
  }
});
```

**Comment by Shtibel** [comment]
+1

**Comment by msach22** [comment]
@Shtibel I've submitted a PR for this - this should go out soon

**Comment by msach22** [comment]
This has been released with v3.4.2

**Comment by msach22** [comment]
@Shtibel You can find the release here: https://github.com/opentok/cordova-plugin-opentok/releases/tag/v3.4.2

PR: https://github.com/opentok/cordova-plugin-opentok/pull/142

**Comment by Shtibel** [comment]
Hi @msach22
Sorry for all the questions.
Did you test the audioLevelUpdated on android ?

**Comment by msach22** [comment]
Yes, the `audioLevelUpdated ` events were set already set in [Android](https://github.com/opentok/cordova-plugin-opentok/blob/master/src/android/OpenTokAndroidPlugin.java#L363), but the JS wrapper was not dispatching them. With the following changes, you can see the events will be dispatched when they are received on the JS layer. https://github.com/opentok/cordova-plugin-opentok/pull/142/files#diff-981b9e90fef5db27c7eb09496bcd327bR113 and https://github.com/opentok/cordova-plugin-opentok/pull/142/files#diff-13b9a487a2528a5301accd6471a3549dR123

Please run this in a sample app and file a new issue if it's not working for you.

**Comment by Shtibel** [comment]
Hi @msach22 
This fix is not working.

when we are doing one on one session the event is working
but when a new user connects to the session the audioLevelUpdate stops working

**Comment by msach22** [comment]
@Shtibel Thanks for sharing. It looks like you filed an issue here: https://github.com/opentok/cordova-plugin-opentok/issues/159

I'm happy to continue the discussion there.
