### ISSUE TITLE
How to get call history and calling time duration.

### ISSUE THREAD

**Issue by LokeshPatel** [opentok/cordova-plugin-opentok#15]
Hi,
Could you please help me or suggest me. How to get calling duration after video calling end.
streamDestroyed return below details but not have call end time or total call duration.
streamDestroyed  return response : 
{"reason":"clientDisconnected","details":{"connectionId":"A9D69333-C41E-46DB-8A4F-29BC93C57332","creationTime":"Wed Jan 24 17:05:17 GMT+05:30 2018","fps":-999,"hasAudio":true,"hasVideo":true,"name":"","streamId":"D6D51D8E-A652-4326-A795-8F30FB736292"},"defaultPrevented":false}

Please suggest me how to get call history.

Thanks in advance :)

**Comment by msach22** [comment]
@LokeshPatel The `streamDestroyed` event does not contain information on what time the stream was destroyed. To get call duration, I recommend you storing the time your user subscribed and comparing it against when your user unsubscribes. Alternatively, you can set up session monitoring through your TokBox account and receive real-time session event callbacks and monitor your session activity from your app server. With the session monitoring, you get information about the following events:
- connectionCreated
- connectionDestroyed
- streamCreated
- streammDestroyed

You can use the `timestamp` value from the `streamCreated` and` streamDestroyed` events that will help you calculate the call duration.

For more information on session monitoring, please visit: https://tokbox.com/developer/guides/session-monitoring/
