### ISSUE TITLE
TBPublisher z-index

### ISSUE THREAD

**Issue by IvoPelayo** [opentok/cordova-plugin-opentok#154]
# Bug Report

**Current behavior**
> When publisher video comes up, its always in front of the view, even when a negative z-indez is passed.

**Steps to reproduce**
> InitPublisher with a negative z-index

**What is the current *bug* behavior?**
> OT.UpdateViews is not updating publisher´s z-index (I can change position).

**What is the expected *correct* behavior?**
> TBPublisher should be behind the view when z-index is negative

**Relevant logs and/or screenshots**
Subscriber with negative z-index is behind the view.
![screenshot_2019-01-23-15-54-19](https://user-images.githubusercontent.com/7936145/51632461-23bc2400-1f2e-11e9-90c0-9e9d09d44f98.png).

**Comment by msach22** [comment]
This is a duplicate issue of: https://github.com/opentok/cordova-plugin-opentok/issues/128
