### ISSUE TITLE
NSCameraUsageDescription Disable

### ISSUE THREAD

**Issue by p-sebastian** [opentok/cordova-plugin-opentok#161]
A way to entirely disable camera usage on plugin, since I use it for SIP interconnect, I just need the audio but I can't get it to not require the camera, as well as disable the creation of the view element for the video, which results in some ugly black boxes.

This is on both iOS/android. using latest cordova, plugin, and on ionic v3

**Comment by msach22** [comment]
@p-sebastian If you do not want to initialize the camera at all, please set the `videoSource` property of `initPublisher` to false:
https://github.com/opentok/cordova-plugin-opentok/blob/master/docs/ot.md#initPublisher

This will not prompt the user for the Camera permissions.
