### ISSUE TITLE
Loading opentokjs when platform is browser

### ISSUE THREAD

**Issue by mark-veenstra** [opentok/cordova-plugin-opentok#17]
Browser is also a platform that could be used on Cordova. Wouldn't it be a good idea to add the opentokjs when platform is browser?

**Comment by mark-veenstra** [comment]
Like this: https://github.com/aoberoi/cordova-plugin-opentokjs/blob/master/plugin.xml

**Comment by msach22** [comment]
Solved by https://github.com/opentok/cordova-plugin-opentok/pull/21
