### ISSUE TITLE
Access denied finding property "vendor.camera.aux.packagelist"

### ISSUE THREAD

**Issue by hamdiwanis** [opentok/cordova-plugin-opentok#178]
plz can you help me, on android when i try to publish a video i get

`Access denied finding property "vendor.camera.aux.packagelist"
    Access denied finding property "vendor.camera.aux.packagelist2"`

thanks

**Comment by adeshpandey** [comment]
Hi @hamdiwanis did you find any solution for this ? For me it is happening if app goes in pause mode then resumes again and not happening all the time it is happening randomly.
