### ISSUE TITLE
getPosition is wrong and takes too much margins and the wrong HTML code is removed from view for the publisher

### ISSUE THREAD

**Issue by mark-veenstra** [opentok/cordova-plugin-opentok#23]
The `getPosition()` within `OTHelpers.coffee`  and the `unpublish` in `OTSession.coffee` are not aware of the `insertMode` of the publisher as described in the JS SDK:
https://tokbox.com/developer/sdks/js/reference/OT.html#initPublisher

To get things working for `insertMode` equals `append` the `getPosition()` should be:
```javascript
getPosition = (divName) ->
  # Get the position of element
  pubDiv = document.getElementById(divName)
  if !pubDiv then return {}
  computedStyle = if window.getComputedStyle then getComputedStyle(pubDiv, null) else {}
  width = pubDiv.offsetWidth
  height = pubDiv.offsetHeight
  curtop = pubDiv.offsetTop
  curleft = pubDiv.offsetLeft
  while(pubDiv = pubDiv.offsetParent)
    curleft += pubDiv.offsetLeft
    curtop += pubDiv.offsetTop
#  marginTop = parseInt(computedStyle.marginTop) || 0
#  marginBottom = parseInt(computedStyle.marginBottom) || 0
#  marginLeft = parseInt(computedStyle.marginLeft) || 0
#  marginRight = parseInt(computedStyle.marginRight) || 0
#
#  return {
#    top:curtop + marginTop
#    left:curleft + marginLeft
#    width:width - (marginLeft + marginRight)
#    height:height - (marginTop + marginBottom)
#  }
  return {
    top:curtop
    left:curleft
    width:width
    height:height
  }
```

And the `unpublish` in `OTSession.coffee` should be : 
```javascript
  unpublish:() ->
    @alreadyPublishing = false
    console.log("JS: Unpublish")
    element = document.getElementById( @publisher.domId )
    if(element)
      # element.parentNode.removeChild(element)
      element.removeChild(element.firstChild);
      element.classList.remove("OT_root", 'OT_publisher', 'OT_subscriber');
      element.removeAttribute("data-streamid");
      TBUpdateObjects()
    return Cordova.exec(TBSuccess, TBError, OTPlugin, "unpublish", [] )
```

**Comment by msach22** [comment]
@mark-veenstra Are you trying to use `insertMode` for the browser or a native device? If you're using it for the browser platform, please use the following SDK: https://static.opentok.com/v2/js/opentok.min.js

This JS wrapper should not be used as a replacement for the JS SDK.

**Comment by mark-veenstra** [comment]
@msach22 We are using the plugin for iOS and Android. And also we use this plugin with the browser builds. We added the possibility to load the correct SDK as follows:
https://github.com/opentok/cordova-plugin-opentok/pull/21/files

But I think even if we do not include the JS SDK in the plugin we still need the append mode instead of replace mode. For example:
- Connect to first session, start publishing and subscribing
- Session is done and we need to start second session on the same view
- Because the replace removed the original DOM the publisher is inserted in incorrect place

**Comment by mark-veenstra** [comment]
My earlier description is a bit off. The plugin does nothing with the insertMode. But it does append the publisher HTML code to the provided container. But when the unpublish method is called. It removes the parent container instead of only the injected publisher HTML code.

Also the getPosition takes the margins from the container and keeps them intact but also applies it to the element itself.
Above fixes both issues. Will apply a PR tomorrow.

**Comment by msach22** [comment]
closed by https://github.com/opentok/cordova-plugin-opentok/pull/24
