### ISSUE TITLE
sessionConnected event not passing connection info

### ISSUE THREAD

**Issue by ljr-gloversure** [opentok/cordova-plugin-opentok#26]
If you want a successful video chat experience, you'll likely need to grab **your** connection id to make sure you don't send signals to yourself etc. Unless you know a better/preferred way of getting your own connection id I would suggest adding this functionality to the 'sessionConnected' function in opentok.js 

Something like this works
```
  TBSession.prototype.sessionConnected = function(event) {
    var sessionConnectedEvent;
    pdebug("sessionConnectedHandler", event);
    this.connection = new TBConnection(event.connection);
    this.connections[event.connection.connectionId] = this.connection;
    sessionConnectedEvent = new TBEvent({
      connection: this.connection 
    });
    this.trigger("sessionConnected", sessionConnectedEvent);
    return this;
  };
```

Currently nothing is returned on the sessionConnected event

Cheers
Lewis

**Comment by mark-veenstra** [comment]
According to the `SessionConnectedEvent` documentation these values are deprecated in the JS SDK, so it does not seem likely to add this in the plugin:
https://tokbox.com/developer/sdks/js/reference/SessionConnectEvent.html

**Comment by ljr-gloversure** [comment]
`
Deprecated in version 2.2 (and set to an empty array). In version 2.2, listen for the connectionCreated event dispatched by the Session object. In version 2.2, the Session object dispatches a connectionCreated event for each connection (including your own). This includes connections present when you first connect to the session.
`

I see, I guess using the connectionCreated event will require you to better 'keep track' of your own connection id. I'm sure there is method behind tokbox getting rid of the SessionConnected event, though personally I don't see the point.
