### ISSUE TITLE
Not all event listeners are implemented

### ISSUE THREAD

**Issue by mark-veenstra** [opentok/cordova-plugin-opentok#30]
There are a few event listeners missing in the plugin, like:
* streamPropertyChanged (Session)

We will send a PR with the missing events implemented.

**Comment by wolfenrain** [comment]
## Session
iOS: 
- [OTSessionDelegate](https://tokbox.com/developer/sdks/ios/reference/Protocols/OTSessionDelegate.html)

Android:
- [ArchiveListener](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.ArchiveListener.html)
- [SessionListener](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.SessionListener.html)
-  [ConnectionListener](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.ConnectionListener.html)
- [Session](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.html)
- [StreamPropertiesListener](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.StreamPropertiesListener.html)

JavaScript | Android | iOS
------------ | ------------- | -------------
archiveStarted | ArchiveListener:onArchiveStarted* | OTSessionDelegate:archiveStartedWithId**
archiveStopped | ArchiveListener:onArchiveStopped* | OTSessionDelegate:archiveStoppedWithId**
sessionConnected | SessionListener:onConnected | OTSessionDelegate:sessionDidConnect
sessionDisconnected | SessionListener:onDisconnected | OTSessionDelegate:sessionDidDisconnect
streamDestroyed | SessionListener:onStreamDropped | OTSessionDelegate:streamDestroyed
streamCreated | SessionListener:onStreamReceived | OTSessionDelegate:streamCreated
connectionCreated | ConnectionListener:onConnectionCreated | OTSessionDelegate:connectionCreated
connectionDestroyed | ConnectionListener:onConnectionDestroyed | OTSessionDelegate:connectionDestroyed
sessionReconnected | Session:onReconnected* | OTSessionDelegate:sessionDidReconnect**
sessionReconnecting | Session:onReconnecting* | OTSessionDelegate:sessionDidBeginReconnecting**
streamPropertyChanged | StreamPropertiesListener:onStreamHasAudioChanged*, StreamPropertiesListener:onStreamHasVideoChanged*, StreamPropertiesListener:onStreamVideoDimensionsChanged*, StreamPropertiesListener:onStreamVideoTypeChanged* | --unknown--**
signal | Session:onSignalReceived | OTSessionDelegate:receivedSignalType**

\* = currently not using implements on Android
\** = not yet implemented on iOS

**Comment by wolfenrain** [comment]
## Publisher
iOS: 
- [OTPublisherDelegate](https://tokbox.com/developer/sdks/ios/reference/Protocols/OTPublisherDelegate.html)
- [OTPublisherKitAudioLevelDelegate](https://tokbox.com/developer/sdks/ios/reference/Protocols/OTPublisherKitAudioLevelDelegate.html)
- [OTPublisherKitDelegate](https://tokbox.com/developer/sdks/ios/reference/Protocols/OTPublisherKitDelegate.html)

Android:
- [AudioLevelListener](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/PublisherKit.AudioLevelListener.html)
- [PublisherListener](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/PublisherKit.PublisherListener.html)
- [CameraListener](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Publisher.CameraListener.html)

JavaScript | Android | iOS
------------ | ------------- | -------------
accessAllowed | --unknown-- | --unknown--
accessDenied | --unknown-- | --unknown--
accessDialogClosed | --unknown-- | --unknown--
accessDialogOpened | --unknown-- | --unknown--
audioLevelUpdated | AudioLevelListener:onAudioLevelUpdated* | OTPublisherKitAudioLevelDelegate:audioLevelUpdated**
mediaStopped | --unknown-- | --unknown--
streamDestroyed | PublisherListener:onStreamDestroyed | OTPublisherKitDelegate:streamDestroyed
streamCreated | PublisherListener:onStreamCreated | OTPublisherKitDelegate:streamCreated
videoDimensionsChanged | --unknown-- | --unknown--
videoElementCreated | --unknown-- | --unknown--
--unknown-- | CameraListener:onCameraChanged | OTPublisherDelegate:didChangeCameraPosition**
--unknown-- | CameraListener:onCameraError | 

\* = currently not using implements on Android
\** = not yet implemented on iOS

**Comment by wolfenrain** [comment]
## Subscriber
iOS: 
- [OTSubscriberKitAudioLevelDelegate](https://tokbox.com/developer/sdks/ios/reference/Protocols/OTSubscriberKitAudioLevelDelegate.html)
- [OTSubscriberDelegate](https://tokbox.com/developer/sdks/ios/reference/Protocols/OTSubscriberDelegate.html)
- [OTSubscriberKitDelegate](https://tokbox.com/developer/sdks/ios/reference/Protocols/OTSubscriberKitDelegate.html)

Android:
- [AudioLevelListener](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/SubscriberKit.AudioLevelListener.html)
- [VideoListener](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/SubscriberKit.VideoListener.html)
- [SubscriberListener](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/SubscriberKit.SubscriberListener.html)

JavaScript | Android | iOS
------------ | ------------- | -------------
audioLevelUpdated | AudioLevelListener:onAudioLevelUpdated* | OTSubscriberKitAudioLevelDelegate:audioLevelUpdated**
connected | SubscriberListener:onConnected | OTSubscriberKitDelegate:subscriberDidConnectToStream
disconnected | SubscriberListener:onDisconnected | OTSubscriberKitDelegate:subscriberDidDisconnectFromStream
destroyed | --uknown-- | --unknown--
videoDimensionsChanged | --unknown-- | --unknown--
videoDisabled | VideoListener:onVideoDisabled | OTSubscriberKitDelegate:subscriberVideoDisabled
videoDisabledWarning | VideoListener:onVideoDisableWarning | OTSubscriberKitDelegate:subscriberVideoDisabledWarning
videoDisabledWarningLifted | VideoListener:onVideoDisableWarningLifted | OTSubscriberKitDelegate:videoDisabledWarningLifted
--unknown-- | VideoListener:onVideoDataReceived | OTSubscriberDelegate:subscribeVideoDataReceived**
videoElementCreated | |
videoEnabled | VideoListener:onVideoEnabled | OTSubscriberKitDelegate:subscriberVideoEnabled

**Note** Not everything has been documented, thinks like reconnect. 

\* = currently not using implements on Android
\** = not yet implemented on iOS
