### ISSUE TITLE
Enabling iOS background mode (audio-only)

### ISSUE THREAD

**Issue by mark-veenstra** [opentok/cordova-plugin-opentok#31]
As describe in the TokBox documentation: https://tokbox.com/developer/sdks/ios/background-state.html
It is possible to have an audio session only when put into background.
We tested this be first adding the correct background mode to the plugin.xml and that should be enough already.

When the banckground mode is set to audio it is enough for switching to audio only. Will send a PR in a sec.

**Comment by msach22** [comment]
closed by: #32
