### ISSUE TITLE
Ionic DevApp Error 

### ISSUE THREAD

**Issue by Giannmit** [opentok/cordova-plugin-opentok#36]
Not sure if this belongs here or opentok-ionic-samples

Check it out:
https://github.com/opentok/opentok-ionic-samples/issues/8

Thanks for your help!

**Comment by mark-veenstra** [comment]
@Giannmit You should add the plugin and use it like @msach22 comments on that issue.

**Comment by msach22** [comment]
@Giannmit closing b/c this is not an issue. please add the cordova plugin to your project
