### ISSUE TITLE
The subscriber functions `subscribeToAudio()` and `subscribeToVideo()` are not yet implemented

### ISSUE THREAD

**Issue by mark-veenstra** [opentok/cordova-plugin-opentok#45]
### Description
The subscriber functions `subscribeToAudio()` and `subscribeToVideo()` are missing in the plugin, both are available through the SDK. So they can be added quite easily.

### `subscribeToAudio()`
* [JS](https://tokbox.com/developer/sdks/js/reference/Subscriber.html#subscribeToVideo)
* [Android](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/SubscriberKit.html#setSubscribeToAudio-boolean-)
* [iOS](https://tokbox.com/developer/sdks/ios/reference/Classes/OTSubscriberKit.html#//api/name/subscribeToAudio)

### `subscribeToVideo()`
* [JS](https://tokbox.com/developer/sdks/js/reference/Subscriber.html#subscribeToVideo)
* [Android](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/SubscriberKit.html#setSubscribeToVideo-boolean-)
* [iOS](https://tokbox.com/developer/sdks/ios/reference/Classes/OTSubscriberKit.html#//api/name/subscribeToVideo)

**Comment by msach22** [comment]
fixed with 3.2.0
