### ISSUE TITLE
Question / Maybe bug

### ISSUE THREAD

**Issue by videmort** [opentok/cordova-plugin-opentok#47]
It's possible to change between cameras any function to do that?
And mute/unmute?
How can I change the width and height of the video. I tried via css but nope ;) (I attach one image on iphone X)
![image1](https://user-images.githubusercontent.com/11390548/36816492-37ac2792-1cde-11e8-9b55-331dd4b24242.png)

**Comment by mark-veenstra** [comment]
* [Changing between front and back camera](https://github.com/opentok/cordova-plugin-opentok/blob/master/www/opentok.js#L441): `publisher.setCameraPosition('front')` or `publisher.setCameraPosition('back')`
* [Mute/unmute](https://github.com/opentok/cordova-plugin-opentok/blob/master/www/opentok.js#L431): `publisher.publishAudio(true)` or `publisher.publishAudio(false)`
* How can I change the width and height of the video: When you dynamically change the width and height after a build, after each CSS change you need to call [`window.OT.updateViews()`](https://github.com/opentok/cordova-plugin-opentok/blob/master/www/opentok.js#L30) method. The webcam is not added within the HTML webview. The webcam is added as a native view which needs to get updated once you change the dimensions.

**Comment by videmort** [comment]
@mark-veenstra thanks I'm going to try

**Comment by msach22** [comment]
@mark-veenstra thanks for answering these again!

**Comment by msach22** [comment]
@videmort closing this b/c it's not an issue with the repo :)
