### ISSUE TITLE
When app resume after tab on notification , session on streamCreated method not work.

### ISSUE THREAD

**Issue by LokeshPatel** [opentok/cordova-plugin-opentok#54]
Hello ,
When Open app after click on notification option, Then start to connect video then streamCreated method not work. if work when app open then method work properly. I've tested on android device.
Could you please help me to solve this issue. I've used below code .

 session = OT.initSession(apiKey, openTokSessionId);
        session.on({
            streamCreated: function(event) {
                console.log("connection active ..... and Apply my login"); 
         // This method not work when app resume form notification or normal as well. if app already open then work fine.
                 onStartStreaming();
             },
            streamDestroyed: function(event) {
                onStopStreaming();
            }
        });

Thanks

**Comment by mark-veenstra** [comment]
Are you sure you wrapped the code into the [deviceReady event](https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.deviceready.html) of Cordova? I am pretty sure it should work.

Also check [the examples](https://github.com/opentok/opentok-cordova-samples/blob/master/Multiparty-Video-Chat/www/js/index.js#L22) which does the same.

**Comment by LokeshPatel** [comment]
Okay, Will check the examples Thanks :)
