### ISSUE TITLE
removeStreamView can trigger an app crash because of async

### ISSUE THREAD

**Issue by wolfenrain** [opentok/cordova-plugin-opentok#55]
If a subscriber decides to leave a session, you get a `onStreamDestroyed` event. But if you try to unsubscribe and the subscriber leaves the session at the same time, then there is a small chance your app will crash because either the `onStreamDestroyed` or the `unsubscribe` triggers `session exception: Cannot unsubscribe: An unknown Subscriber instance was passed into Session.unsubscribe()`.

That is because they both call the `removeStreamView()` natively on the `UiThread` which causes them to be async. The chance of this happening is small, but could be prevented by putting a try catch around the unsubscribe I belief.

I will test this further and on success deliver a PR.

**Comment by wolfenrain** [comment]
The crash is not happening because of the said exception above. Will try to dig into it more.

**Comment by msach22** [comment]
fixed with PR
