### ISSUE TITLE
Getting failed to restore plugin error when trying to add this plugin

### ISSUE THREAD

**Issue by sm20030** [opentok/cordova-plugin-opentok#56]
We get the following error when doing ionic platform add android.

This however, works rarely but mostly fails.  Our connection seems to be fine because other plugins are updated.

Discovered plugin "com.tokbox.cordova.opentok" in config.xml. Adding it to the project
Failed to restore plugin "com.tokbox.cordova.opentok" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin com.tokbox.cordova.opentok@https://github.com/opentok/cordova-plugin-opentok via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**Comment by mark-veenstra** [comment]
This issue will be solved in `3.2.0` since the solution of correct plugin naming.

**Comment by msach22** [comment]
fixed with 3.2.0. Please download 3.2.0
