### ISSUE TITLE
TBSubscriber does not have stream object

### ISSUE THREAD

**Issue by wolfenrain** [opentok/cordova-plugin-opentok#70]
# Bug Report

**Current behavior**
> According to the [WebSDK](https://tokbox.com/developer/sdks/js/reference/Subscriber.html), the subscriber should have a `Stream` property. 

**Steps to reproduce**
> Just check it

**Example Project**
> Any project using current branch

**What is the current *bug* behavior?**
> No `Stream` property on subscribers.

**What is the expected *correct* behavior?**
> A `Stream` property on subscribers

**Comment by msach22** [comment]
This should go out with `3.3.0`

**Comment by msach22** [comment]
Released with `3.3.0`
